/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {
    public static void main(String[] args) {
        Arara a = new Arara("Erik");
        Avestruz av = new Avestruz("Antonio");
        Baleia b = new Baleia("Jubileu");
        Cachorro c = new Cachorro("Erik");

        System.out.println(a.habilidade());
        System.out.println(av.habilidade());
        System.out.println(b.habilidade());
        System.out.println(c.habilidade());
    }
}
