/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

import edu.princeton.cs.algs4.Draw;
import edu.princeton.cs.algs4.DrawListener;

import java.awt.image.BandedSampleModel;
import java.util.Random;

public class App implements DrawListener {

    Draw draw = new Draw();

    public App() {
        this.draw = new Draw();
        this.draw.addListener(this);
        this.draw.show();
    }

    @Override
    public void keyTyped(char c) {
        if (c == 'l') {
            this.draw.clear();
        }
    }

    @Override
    public void mousePressed(double x, double y) {

        Random r = new Random();
        double d = r.nextDouble(0.1, 0.5);

        Bandeira bandeira = new Bandeira(x, y, d);
        bandeira.desenhar(draw);

    }

    public static void main(String[] args) {


//        draw.rectangle(.5, .5, .4, .25);
//        draw.setPenColor(255,0,0);
//        draw.filledCircle(.5, .5, .15);

        App app = new App();
    }
}
