/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

import ads.poo.jogo.Aldeao;
import ads.poo.jogo.Arqueiro;
import ads.poo.jogo.Cavaleiro;

public class App {
    public static void main(String[] args) {
        Aldeao aldeao = new Aldeao();
        Arqueiro arqueiro = new Arqueiro();
        Cavaleiro cavaleiro = new Cavaleiro();

        System.out.println(aldeao.atacar());
        System.out.println(arqueiro.atacar());
        System.out.println(cavaleiro.atacar());

        System.out.println(aldeao.mover());
        System.out.println(arqueiro.mover());
        System.out.println(cavaleiro.mover());
    }
}
